require_relative 'subscriptions_test_kit/metadata'
require_relative 'subscriptions_test_kit/suites/subscriptions_r5_backport_r4_server_suite'
require_relative 'subscriptions_test_kit/suites/subscriptions_r5_backport_r4_client_suite'
