name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_requirements:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1.2"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run requirements coveage check
        run: bundle exec rake requirements:check_coverage
